#!/usr/bin/env bash

EXP='s/(password:\s+|auth:\s+)".*?" => ".*?"/\1"********" => "********" [hidden]/g'

if [ "$(uname)" == 'Darwin' ]; then
  # BSD sed
  sed -E "$EXP"
else
  # GNU sed
  sed -u -r -e "$EXP"
fi
